### ISSUE TITLE
How to call xmlstarlet from a bash script

### ISSUE THREAD

**Issue by andry81** [Mudlet/xmlstarlet-action#7]
Just wanted to enlight the problem. I've wanted to call xmlstarlet from the bash script which already being called from a GitHub action script. But because the `runs-on: ubuntu-latest` does not include it, then I have, for example, to use the xmlstarlet from the docker image, which I can not use from the inner call to the bash script.

(1) Schema which I want and can not be used:

`GitHub Action` -> `Bash script` -> `GitHub Action (Docker Image)`

(2) Schema which suggested by the GitHub pipeline:

`GitHub Action` -> `GitHub Action (Docker Image)` -> `Bash script`

This is a pretty serious problem, because to use a nested call into GitHub Actions pipeline (in this case the docker image) I have to rewrite all scripts to avoid a call from it. In other words I can not reuse already written code and scripts from the GitHub Actions pipeline with a nested call. I have to just drop them which is not affordable at all.

Is there a way to somehow workaround that without rewrite or drop already written code and scripts?

**Comment by vadi2** [comment]
@keneanung would you know?

**Comment by keneanung** [comment]
From what I understand, you have a bash script that you want to run on GitHub Actions without modifying, which uses xmlstarlet.

The easiest way would be to simply install xmstarlet in a step before running your bash script:
```
- name: Install xmlstarlet
  run: sudo apt-get install -y xmstarlet
```

If that doesn't work for you for some reason and you have to run a dockerized version, either create and push your own image (you can have a look at the `entrypoint.sh` and `Dockerfile` files in this repo how). Or if you want to use this image here, my idea is pretty involved:
1. clone this repository
2. build the docker image
3. create an alias `xmlstarlet` that runs the docker image

I realize this comment doesn't include exact commands to run as I'm away from my usual environment. But if you need further assistance, comment here and we'll work something out.

**Comment by andry81** [comment]
Thx! Evently I've already found this too: https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-actions-workflow

I didn't know the `sudo` is passwordless under the `ubuntu-latest`.

By the way, I have tested and the xmlstarlet docker image is 50% slower (~13s) than `apt-get install xmlstarlet` (~7.5s).

**Comment by andry81** [comment]
For those who searching for implementations: https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow/73500415#73500415
