### ISSUE TITLE
set-output is going depreciated

### ISSUE THREAD

**Issue by n6171028** [Mudlet/xmlstarlet-action#8]
Hi, the set-output is going depreciated and I receives warnings when use xmlstarlet, could you use the Github recommended way to save output to $GITHUB_OUTPUT please?

**Comment by keneanung** [comment]
:thumbsup: ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by n6171028** [comment]
yeah the entrypoint.sh needs to be updated
